[package]
description = "rolldown_runtime_helpers"
edition     = "2021"
license     = "MIT"
name        = "rolldown_runtime_helpers"
version     = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
