[package]
name = "rolldown_swc_utils"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "rolldown_swc_utils"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_core = { workspace = true, features = ["ecma_ast"] }